// export * from './cookies';
// export * from './localStorage';
// export * from './dateDB';
// export * from './fetchAPI';
// export * from './find_id';
// export * from './barCode';
// export * from './fetchAndSetAll';
// export * from './getApptFromDbSched';
// export * from './nullOrUndefined';
// export * from './haveCheckedItem';
// export * from './buildFollowups';
// export * from './fileHandler';
// export * from './handleBrokenImage';
export * from './fetch';